[package]
name = "Tehran"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "0.46.0",features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"]}
sha2 = {version = "0.10.6"}

[lib]
crate-type = ["cdylib"]
#crate-type = ["bin"]